### ISSUE TITLE
clean code of several modules

### ISSUE THREAD

**Issue by QiJune** [sql-machine-learning/elasticdl#1196]
- [x] Move lookup embedding from worker to embedding layer #1182 
- [ ] Move initializing parameter logic from worker to master #1185 
- [ ] Refine embedding service and clean interface #1194 
- [ ] Split pserver service from master, move embedding service to pserver service module

**Comment by brightcoder01** [comment]
All the work in this issue is done.
Close the out-of-date issue.
